# Generated by Django 3.2.6 on 2021-08-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account_type',
            options={'verbose_name': 'Account Type'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='entry_type',
            options={'verbose_name': 'Expense entry type'},
        ),
        migrations.AlterModelOptions(
            name='entry_type_category',
            options={'verbose_name': 'Expense entry category', 'verbose_name_plural': 'Expense entry categories'},
        ),
        migrations.AddField(
            model_name='account_type',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='entry',
            name='memo',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
