version: "3.1"

services:
  db:
    image: postgres
    restart: always
    volumes: 
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=expense
      - POSTGRES_USER=expense
      - POSTGRES_PASSWORD=wq#b0xn_5mhl8m*hi^7ad(6t#th&wl_@+&i-sw7e86+ca2n!
    ports:
      - 5847:5432
    user: 1000:1000
      
  adminer:
    image: adminer
    ports:
      - 5848:8080
